
-- TETRA-IRRATIAK / Supabase
-- Run this script once in Supabase SQL Editor.
create table if not exists public.irratia (
  id bigint primary key,
  zka bigint,
  alias text,
  mota text,
  marka text,
  modelo text,
  gps boolean not null default false,
  gateway boolean not null default false,
  tei bigint,
  baja_definitiva boolean not null default false,
  sustituido boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mugimenduak (
  id bigint generated by default as identity primary key,
  radio_id bigint references public.irratia(id) on delete set null,
  nork text,
  noiztik date,
  noizarte date,
  zergatia text,
  bateria numeric,
  funda boolean not null default false,
  micro boolean not null default false,
  karga boolean not null default false,
  kablea_12v boolean not null default false,
  arreta numeric,
  teltronic text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_irratia_zka on public.irratia(zka);
create index if not exists idx_irratia_alias on public.irratia(alias);
create index if not exists idx_mugimenduak_radio_id on public.mugimenduak(radio_id);
create index if not exists idx_mugimenduak_nork on public.mugimenduak(nork);
create index if not exists idx_mugimenduak_noiztik on public.mugimenduak(noiztik);

alter table public.irratia enable row level security;
alter table public.mugimenduak enable row level security;

drop policy if exists "authenticated read irratia" on public.irratia;
drop policy if exists "authenticated insert irratia" on public.irratia;
drop policy if exists "authenticated update irratia" on public.irratia;
drop policy if exists "authenticated delete irratia" on public.irratia;

create policy "authenticated read irratia" on public.irratia
for select to authenticated using (true);
create policy "authenticated insert irratia" on public.irratia
for insert to authenticated with check (true);
create policy "authenticated update irratia" on public.irratia
for update to authenticated using (true) with check (true);
create policy "authenticated delete irratia" on public.irratia
for delete to authenticated using (true);

drop policy if exists "authenticated read mugimenduak" on public.mugimenduak;
drop policy if exists "authenticated insert mugimenduak" on public.mugimenduak;
drop policy if exists "authenticated update mugimenduak" on public.mugimenduak;
drop policy if exists "authenticated delete mugimenduak" on public.mugimenduak;

create policy "authenticated read mugimenduak" on public.mugimenduak
for select to authenticated using (true);
create policy "authenticated insert mugimenduak" on public.mugimenduak
for insert to authenticated with check (true);
create policy "authenticated update mugimenduak" on public.mugimenduak
for update to authenticated using (true) with check (true);
create policy "authenticated delete mugimenduak" on public.mugimenduak
for delete to authenticated using (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists irratia_updated_at on public.irratia;
create trigger irratia_updated_at before update on public.irratia
for each row execute function public.set_updated_at();

drop trigger if exists mugimenduak_updated_at on public.mugimenduak;
create trigger mugimenduak_updated_at before update on public.mugimenduak
for each row execute function public.set_updated_at();
